// <auto-generated />
using DataAcess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251216095921_AddProductToDb")]
    partial class AddProductToDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Hành động"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Alime"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Khoa học"
                        });
                });

            modelBuilder.Entity("Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price100")
                        .HasColumnType("float");

                    b.Property<double>("Price500")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Tô Hoài",
                            Description = "Tác phẩm văn học thiếu nhi kinh điển kể về những cuộc phiêu lưu đầy thú vị và bài học làm người của chú Dế Mèn.",
                            ISBN = "VN-DM001",
                            ListPrice = 60000.0,
                            Price = 55000.0,
                            Price100 = 50000.0,
                            Price500 = 45000.0,
                            Title = "Dế Mèn Phiêu Lưu Ký"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Nguyễn Nhật Ánh",
                            Description = "Câu chuyện tình đơn phương day dứt của Ngạn dành cho Hà Lan, gắn liền với ngôi làng Đo Đo và những kỷ niệm tuổi thơ.",
                            ISBN = "VN-MB002",
                            ListPrice = 110000.0,
                            Price = 100000.0,
                            Price100 = 95000.0,
                            Price500 = 90000.0,
                            Title = "Mắt Biếc"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Vũ Trọng Phụng",
                            Description = "Tiểu thuyết trào phúng xuất sắc đả kích xã hội tư sản thành thị Việt Nam trước năm 1945 qua nhân vật Xuân Tóc Đỏ.",
                            ISBN = "VN-SD003",
                            ListPrice = 85000.0,
                            Price = 80000.0,
                            Price100 = 75000.0,
                            Price500 = 70000.0,
                            Title = "Số Đỏ"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Đoàn Giỏi",
                            Description = "Hành trình lưu lạc của cậu bé An tìm cha trong bối cảnh thiên nhiên hoang sơ và con người hào sảng của vùng Nam Bộ.",
                            ISBN = "VN-DRPN004",
                            ListPrice = 95000.0,
                            Price = 90000.0,
                            Price100 = 85000.0,
                            Price500 = 80000.0,
                            Title = "Đất Rừng Phương Nam"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Nguyễn Nhật Ánh",
                            Description = "Cuốn sách đưa người đọc trở về thế giới tuổi thơ hồn nhiên, tinh nghịch với những suy nghĩ vừa non nớt vừa triết lý.",
                            ISBN = "VN-VTT005",
                            ListPrice = 100000.0,
                            Price = 95000.0,
                            Price100 = 85000.0,
                            Price500 = 80000.0,
                            Title = "Cho Tôi Xin Một Vé Đi Tuổi Thơ"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Nguyễn Ngọc Tư",
                            Description = "Tuyển tập truyện ngắn khắc họa sâu sắc số phận của những người nông dân miền Tây sông nước với nỗi buồn man mác.",
                            ISBN = "VN-CDBT006",
                            ListPrice = 75000.0,
                            Price = 70000.0,
                            Price100 = 65000.0,
                            Price500 = 60000.0,
                            Title = "Cánh Đồng Bất Tận"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
